### ISSUE TITLE
Did you mean rint ?

### ISSUE THREAD

**Issue by YvanoffP** [Bima42/troncCommun#1]
https://github.com/Bima42/troncCommun/blob/633db25d8cdf7630ca44742c7596cea3e2d288a2/born2beroot/script.txt#L28

**Comment by Bima42** [comment]
Try this on the terminal : free -m | awk 'NR==2{printf "%s/%sMB (%.2f%%)", $3,$2,$3*100/$2 }' 

It work for me dude
